#!/bin/bash
set -e

IS_WIN=false
DIFF=diff
# if MinGW
if [ "$COMSPEC" != "" ]; then
	IS_WIN=true
	DIFF=/b/bin/diff
fi

# JUMAN++ Apache 2.0
JUMANPP_URL=http://lotus.kuee.kyoto-u.ac.jp/nl-resource/jumanpp/jumanpp-1.02.tar.xz
# Boost C++ Library
BOOSTLIB_URL=https://dl.bintray.com/boostorg/release/1.65.1/source/boost_1_65_1.zip
DOWNLOADS="$JUMANPP_URL"

# Environment
THIS_DIR=cexe
THIS_ABS=$PWD

JUMANPP=jumanpp-1.02
ARCHIVE=${JUMANPP}.tar.xz
PACKAGE=${JUMANPP}
ARCHIVE_DIR=archives

TEST_DIR=test
TEST_EXE=./test.sh

PACKAGE_DIR=${PACKAGE}
PATCH_FILE=${ARCHIVE_DIR}/ext_${PACKAGE}_02.patch
DIST_NAME=${JUMANPP}_ext
DIST_DIR=dist

PREFIX=${PWD}/${DIST_DIR}/${DIST_NAME}
INCLUDE_DIR=${THIS_ABS}/local/include
CPPFLAGS="-I${INCLUDE_DIR}"

if $IS_WIN; then
	# For Windows. (MinGW)
	# PREFIX=
	LDFLAGS="--static -static-libgcc -static-libstdc++"
	LIBS="-lwinpthread -liconv"
	INCLUDE_DIR=${THIS_ABS}/local_win/include
	CPPFLAGS="-I${INCLUDE_DIR}"
else
	# For POSIX systems
	#PREFIX="$HOME/local"
	PREFIX=${PREFIX}_$(uname)
	CPPFLAGS="${CPPFLAGS} -Ofast -march=native -funroll-loops -ffast-math"
	LDFLAGS=
	LIBS=
fi

# configure to install.
# @param dist_dir for prefix
# @param flags for CPPFLAGS
function build_all() {
	cd $PACKAGE_DIR
	if $IS_WIN; then
		mkdir -p $1
		rm -rf $1/*
		echo ./configure --prefix=$1 --bindir=$1 --enable-no-dict \
			LDFLAGS="${LDFLAGS}" LIBS="${LIBS}" CPPFLAGS="$2" \
			CFLAGS="" CXXFLAGS=""
		./configure --prefix=$1 --bindir=$1 --enable-no-dict \
			LDFLAGS="${LDFLAGS}" LIBS="${LIBS}" CPPFLAGS="$2" \
			CFLAGS="" CXXFLAGS=""
		make clean all install
	else
		echo ./configure --prefix=$1 --enable-no-dict \
			LDFLAGS="${LDFLAGS}" LIBS="${LIBS}" CPPFLAGS="$2" \
			CFLAGS="" CXXFLAGS=""
		./configure --prefix=$1 --enable-no-dict \
			LDFLAGS="${LDFLAGS}" LIBS="${LIBS}" CPPFLAGS="$2" \
			CFLAGS="" CXXFLAGS=""
		make clean all install
	fi
	cd ..
}

# make and install resources
# @param dist_dir for prefix
function make_rs() {
	make -C ${PACKAGE_DIR}/dict-build all
	make -C ${PACKAGE_DIR}/jumanpp-resource clean all
	if [ "$1" != "" ]; then
		make -C ${PACKAGE_DIR}/jumanpp-resource install prefix=$1
	fi
}

# Align distribute director for Windows
# @param prefix
function align() {
	if $IS_WIN; then
		curdir=$PWD
		cd $1
		mv share/jumanpp ./dics
		rm -rf share
		cp ${curdir}/${PACKAGE_DIR}/jumanpp-manual.pdf .
		cp ${curdir}/scripts/jumanpp-i.bat .
		cp ${curdir}/scripts/copying.win.txt copying.txt
		cp ${curdir}/scripts/make_rs.bat dics
		cd $curdir
	fi
}

echo ${JUMANPP}_EXT

for cmd in $*; do

if [ $cmd = "download" ]; then
	cd $ARCHIVE_DIR
	for download in $DOWNLOADS ; do
#		if [ ! -e basename $download ]; then
			wget $download
#		fi
	done
	cd ..

elif [ $cmd = "load" ]; then
	mkdir -p local_win/include
	unzip ${ARCHIVE_DIR}/boost-1_65_subset.zip -d local_win/include
	tar xf ${ARCHIVE_DIR}/${ARCHIVE}
	cd $PACKAGE_DIR
	patch -p1 < ../${PATCH_FILE}
	mkdir -p backup/dict-build backup/jumanpp-resource
	mv jumanpp-resource/dic.* backup/jumanpp-resource
	mv jumanpp-resource/version backup/jumanpp-resource
	mv dict-build/Makefile backup/dict-build
	cd ..
	cp ${ARCHIVE_DIR}/Makefile.dict-build ${PACKAGE_DIR}/dict-build/Makefile
	cp ${ARCHIVE_DIR}/Makefile.jumanpp-resource ${PACKAGE_DIR}/jumanpp-resource/Makefile

elif [ $cmd = "build" ]; then
	build_all $PREFIX "${CPPFLAGS}"
	make_rs $PREFIX

elif [ $cmd = "build-w64" ]; then
	n_dist=${PREFIX}_win64
	build_all ${n_dist} "${CPPFLAGS} -m64 -Ofast"
	make -C ${PACKAGE_DIR}/dict-build all install prefix=${n_dist}
	make -C ${PACKAGE_DIR}/jumanpp-resource install-mdl prefix=${n_dist}
	align ${n_dist}

# For develop

elif [ $cmd = "build-dic" ]; then
	make_rs

elif [ $cmd = "build-debug" ]; then
	n_dist=${PREFIX}_debug
	build_all ${n_dist} "${CPPFLAGS} -g -O0"
	align ${n_dist}

elif [ $cmd = "diff" ]; then
	diff_opt="-rupBN -x stamp-h1 -x winconf -x jumanpprc -x libtool -x .libs -x .deps -x config.* -x *.log -x *.o -x *.lo -x *.a -x *.la -x *.so -x *.exe -x Makefile"
	fromdir=/tmp/${PACKAGE_DIR}
	todir=${PACKAGE_DIR}
	cp ${todir}/dict-build/Makefile ${ARCHIVE_DIR}/Makefile.dict-build
	cp ${todir}/jumanpp-resource/Makefile ${ARCHIVE_DIR}/Makefile.jumanpp-resource
	$DIFF ${diff_opt} ${fromdir}/src ${todir}/src > ${PATCH_FILE}

elif [ $cmd = "test" ]; then
	if $IS_WIN; then
		cd $TEST_DIR
#		$TEST_EXE
		$TEST_EXE ../${DIST_DIR}/${DIST_NAME}_win64/jumanpp.exe
#		$TEST_EXE ../dist/juman-7.01_ext_win32/juman.exe
		cd ..
	else
		cd $TEST_DIR
		$TEST_EXE ${PREFIX}/bin/juman
		cd ..
	fi

elif [ $cmd = "clean-dist" ]; then
	rm -rf ${DIST_DIR}/*

elif [ $cmd = "zip" ]; then
	cp scripts/copying.win.txt ${DIST_DIR}/${DIST_NAME}_win64/copying.txt
#	cp copyings/copying.exe.txt ${DIST_DIR}/${DIST_NAME}_win32/copying.txt
	cd ${DIST_DIR}
	rm -f ${DIST_NAME}-${MODULE_VERSION}_win64.zip
	zip -r ${DIST_NAME}-${MODULE_VERSION}_win64.zip ${DIST_NAME}_win64
#	zip -r ${DIST_NAME}-${MODULE_VERSION}_win32.zip ${DIST_NAME}_win32
	cd ..

elif [ $cmd = "git-push" ]; then
	cd ..
	git push origin master
	cd $THIS_DIR

elif [ $cmd = "git-tag" ]; then
	cd ..
	echo -n "Comment: "
	read comm
	git tag -a $V_VERSION -m "${comm}"
	git push origin $V_VERSION
	cd $THIS_DIR

else
	echo "Unknown command:" $cmd
	break
fi

done
